spectaql:
  logoFile: ./icons/logo.png
  faviconFile: ./icons/logo.png
  displayAllServers: true

introspection:
  url: https://x2zpvsawy5hatarddisdsrpwva.appsync-api.ap-southeast-1.amazonaws.com/graphql
  headers:
    x-api-key: da2-bwl2iyelpngehpeibkilozu2jq
  removeTrailingPeriodFromDescriptions: false
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

extensions:
  graphqlScalarExamples: true

info:
  title: TheSocialPitstop GraphQL API Reference
  description: This is the documentation for TheSocialPitstop's GraphQL API.
  termsOfService: https://www.example.com/terms (Placeholder)
  contact:
    name: TheSocialPitstop Support
    url: https://thesocialpitstop.vercel.app/contact-us (to be created)
    # email: tsp.orbital@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-introItems:
    - title: Placeholder Title
      description: Placeholder Description

servers:
  - url: https://x2zpvsawy5hatarddisdsrpwva.appsync-api.ap-southeast-1.amazonaws.com/graphql
    production: true
    headers:
      - x-api-key: da2-bwl2iyelpngehpeibkilozu2jq